### ISSUE TITLE
use collation strength of 1 to allow search indices that ignore case and diacritics

### ISSUE THREAD

**Issue by ramcdougal** [mcdougallab/modeldb#102]
https://docs.mongodb.com/manual/reference/collation/#std-label-collation-document-fields

**Comment by goldiezhu** [comment]
Fixed with all_author_accent_mapping in models.py.
Example below:
>>> all_authors                                                                                                                                                                 
{'Zhu G', 'Fernández H', 'Crane GJ'}
>>> all_author_accent_mapping
{'fernandez h': ['Fernández H']}
>>> author = 'Fernández H'
>>> find_authors(author)
['Fernández H']
>>> find_authors('Fernandez H')
['Fernández H']
>>> find_authors('Fernandez h')
['Fernández H']
>>> find_authors('zhu g')
['Zhu G']
