### ISSUE TITLE
Login doesn't work on Mobile

### ISSUE THREAD

**Issue by ramcdougal** [mcdougallab/modeldb#196]
It just redirects to the home page.

**Comment by ramcdougal** [comment]
The problem is that the site image is too big and invisibly overlaps the word login. We tried changing the z-index, but didn't find a way that didn't cause other problems. Maybe the right fix is to figure out why the site image is so big.

**Comment by yhy808** [comment]
Cropping the icon image's right-bottom portion using "clip-path" might solve this problem. The "clip-path" property specifies a rectangular area to display without modifying the image file itself. 

Here is the modified one-line HTML code:
<img class="d-inline-block align-top" src="/static/modeldb/modeldb-icon.svg"
     style="width: 4em; position: absolute; left: 0em; top: 0em; clip-path: inset(0 1em 1em 0);">

**Comment by yhy808** [comment]
To modify the svg image, I changed the viewBox to place the icon in the center and make it smaller. 

Code change in "/static/modeldb/modeldb-icon.svg":
```
width="26" height="24" viewBox="0 10 130 100"
```
