### ISSUE TITLE
Model 86537 readme images do not show

### ISSUE THREAD

**Issue by Muktadir-Chowdhury** [mcdougallab/modeldb#198]

**Comment by ramcdougal** [comment]
This turned out to be a curation issue because the image file names ended in `.JPG` but the readme was looking for `.jpg` so they were considered different files on our linux-based system.

**Comment by Muktadir-Chowdhury** [comment]
Oh I see, file extensions are case-sensitive in Linux as opposed to file extensions in Windows.
